# -*- coding: utf-8 -*-
"""test_from_tensor_slices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15MV4RrBXLrBYTuACGQmufTmWctOB8SaJ
"""

import tensorflow as tf

tensor1 = tf.constant(value = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
tensor2 = tf.constant(value = [20, 21, 22, 23])

tf.print(tensor1.shape)
tf.print(tensor2.shape)

dataset = tf.data.Dataset.from_tensor_slices((tensor1, tensor2))

print('\nOriginal dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.repeat(3)

print('\nRepeated dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.shuffle(3)

print('\nShuffled dataset')
for i in dataset:
      tf.print(i)

dataset = dataset.batch(2)

print('\n*******************')
print('* Batched dataset * ')
print('*******************')
for i in dataset:
      tf.print(i)

dataset = dataset.prefetch(1)

print('\nPrefetched dataset')
for i in dataset:
      tf.print(i)

print('\nDataset take')
for iter, (temp1, temp2) in enumerate(dataset.take(2), 1):
  print('Iteration number {}'.format(iter))
  tf.print('Features batch {}'.format(temp1))
  tf.print('Classes batch {}'.format(temp2))